// Code generated by goctl. DO NOT EDIT!
// Source: banner.proto

package bannersrv

import (
	"context"

	"looklook/app/banner/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Banner         = pb.Banner
	BannerInfoReq  = pb.BannerInfoReq
	BannerInfoResp = pb.BannerInfoResp

	BannerSrv interface {
		// 广告详情
		BannerInfo(ctx context.Context, in *BannerInfoReq, opts ...grpc.CallOption) (*BannerInfoResp, error)
	}

	defaultBannerSrv struct {
		cli zrpc.Client
	}
)

func NewBannerSrv(cli zrpc.Client) BannerSrv {
	return &defaultBannerSrv{
		cli: cli,
	}
}

// 广告详情
func (m *defaultBannerSrv) BannerInfo(ctx context.Context, in *BannerInfoReq, opts ...grpc.CallOption) (*BannerInfoResp, error) {
	client := pb.NewBannerSrvClient(m.cli.Conn())
	return client.BannerInfo(ctx, in, opts...)
}
