// Code generated by goctl. DO NOT EDIT!
// Source: mqueue.proto

package mqueue

import (
	"context"

	"looklook/app/mqueue/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AqDeferHomestayOrderCloseReq  = pb.AqDeferHomestayOrderCloseReq
	AqDeferHomestayOrderCloseResp = pb.AqDeferHomestayOrderCloseResp
	KqPaymenStatusUpdateReq       = pb.KqPaymenStatusUpdateReq
	KqPaymenStatusUpdateResp      = pb.KqPaymenStatusUpdateResp
	SendWxMiniSubMessageReq       = pb.SendWxMiniSubMessageReq
	SendWxMiniSubMessageResp      = pb.SendWxMiniSubMessageResp

	Mqueue interface {
		// 添加民宿订单延迟关闭到asynq队列
		AqDeferHomestayOrderClose(ctx context.Context, in *AqDeferHomestayOrderCloseReq, opts ...grpc.CallOption) (*AqDeferHomestayOrderCloseResp, error)
		// 支付流水状态变更发送到kq
		KqPaymenStatusUpdate(ctx context.Context, in *KqPaymenStatusUpdateReq, opts ...grpc.CallOption) (*KqPaymenStatusUpdateResp, error)
		// 发送微信小程序订阅消息
		SendWxMiniSubMessage(ctx context.Context, in *SendWxMiniSubMessageReq, opts ...grpc.CallOption) (*SendWxMiniSubMessageResp, error)
	}

	defaultMqueue struct {
		cli zrpc.Client
	}
)

func NewMqueue(cli zrpc.Client) Mqueue {
	return &defaultMqueue{
		cli: cli,
	}
}

// 添加民宿订单延迟关闭到asynq队列
func (m *defaultMqueue) AqDeferHomestayOrderClose(ctx context.Context, in *AqDeferHomestayOrderCloseReq, opts ...grpc.CallOption) (*AqDeferHomestayOrderCloseResp, error) {
	client := pb.NewMqueueClient(m.cli.Conn())
	return client.AqDeferHomestayOrderClose(ctx, in, opts...)
}

// 支付流水状态变更发送到kq
func (m *defaultMqueue) KqPaymenStatusUpdate(ctx context.Context, in *KqPaymenStatusUpdateReq, opts ...grpc.CallOption) (*KqPaymenStatusUpdateResp, error) {
	client := pb.NewMqueueClient(m.cli.Conn())
	return client.KqPaymenStatusUpdate(ctx, in, opts...)
}

// 发送微信小程序订阅消息
func (m *defaultMqueue) SendWxMiniSubMessage(ctx context.Context, in *SendWxMiniSubMessageReq, opts ...grpc.CallOption) (*SendWxMiniSubMessageResp, error) {
	client := pb.NewMqueueClient(m.cli.Conn())
	return client.SendWxMiniSubMessage(ctx, in, opts...)
}
