// Code generated by goctl. DO NOT EDIT!
// Source: banner.proto

package server

import (
	"context"

	"looklook/app/banner/cmd/rpc/internal/logic"
	"looklook/app/banner/cmd/rpc/internal/svc"
	"looklook/app/banner/cmd/rpc/pb"
)

type BannerSrvServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedBannerSrvServer
}

func NewBannerSrvServer(svcCtx *svc.ServiceContext) *BannerSrvServer {
	return &BannerSrvServer{
		svcCtx: svcCtx,
	}
}

// 广告详情
func (s *BannerSrvServer) BannerInfo(ctx context.Context, in *pb.BannerInfoReq) (*pb.BannerInfoResp, error) {
	l := logic.NewBannerInfoLogic(ctx, s.svcCtx)
	return l.BannerInfo(in)
}
