// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: mqueue.proto

//消息队列

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AqDeferHomestayOrderCloseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sn string `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn"`
}

func (x *AqDeferHomestayOrderCloseReq) Reset() {
	*x = AqDeferHomestayOrderCloseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqueue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AqDeferHomestayOrderCloseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AqDeferHomestayOrderCloseReq) ProtoMessage() {}

func (x *AqDeferHomestayOrderCloseReq) ProtoReflect() protoreflect.Message {
	mi := &file_mqueue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AqDeferHomestayOrderCloseReq.ProtoReflect.Descriptor instead.
func (*AqDeferHomestayOrderCloseReq) Descriptor() ([]byte, []int) {
	return file_mqueue_proto_rawDescGZIP(), []int{0}
}

func (x *AqDeferHomestayOrderCloseReq) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

type AqDeferHomestayOrderCloseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AqDeferHomestayOrderCloseResp) Reset() {
	*x = AqDeferHomestayOrderCloseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqueue_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AqDeferHomestayOrderCloseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AqDeferHomestayOrderCloseResp) ProtoMessage() {}

func (x *AqDeferHomestayOrderCloseResp) ProtoReflect() protoreflect.Message {
	mi := &file_mqueue_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AqDeferHomestayOrderCloseResp.ProtoReflect.Descriptor instead.
func (*AqDeferHomestayOrderCloseResp) Descriptor() ([]byte, []int) {
	return file_mqueue_proto_rawDescGZIP(), []int{1}
}

type KqPaymenStatusUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderSn   string `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn"`
	PayStatus int64  `protobuf:"varint,2,opt,name=payStatus,proto3" json:"payStatus"`
}

func (x *KqPaymenStatusUpdateReq) Reset() {
	*x = KqPaymenStatusUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqueue_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KqPaymenStatusUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KqPaymenStatusUpdateReq) ProtoMessage() {}

func (x *KqPaymenStatusUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_mqueue_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KqPaymenStatusUpdateReq.ProtoReflect.Descriptor instead.
func (*KqPaymenStatusUpdateReq) Descriptor() ([]byte, []int) {
	return file_mqueue_proto_rawDescGZIP(), []int{2}
}

func (x *KqPaymenStatusUpdateReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *KqPaymenStatusUpdateReq) GetPayStatus() int64 {
	if x != nil {
		return x.PayStatus
	}
	return 0
}

type KqPaymenStatusUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KqPaymenStatusUpdateResp) Reset() {
	*x = KqPaymenStatusUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqueue_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KqPaymenStatusUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KqPaymenStatusUpdateResp) ProtoMessage() {}

func (x *KqPaymenStatusUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_mqueue_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KqPaymenStatusUpdateResp.ProtoReflect.Descriptor instead.
func (*KqPaymenStatusUpdateResp) Descriptor() ([]byte, []int) {
	return file_mqueue_proto_rawDescGZIP(), []int{3}
}

type SendWxMiniSubMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Openid     string            `protobuf:"bytes,1,opt,name=Openid,proto3" json:"Openid"`
	TemplateID string            `protobuf:"bytes,2,opt,name=TemplateID,proto3" json:"TemplateID"`
	Page       string            `protobuf:"bytes,3,opt,name=Page,proto3" json:"Page"`
	Data       map[string]string `protobuf:"bytes,4,rep,name=Data,proto3" json:"Data" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SendWxMiniSubMessageReq) Reset() {
	*x = SendWxMiniSubMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqueue_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendWxMiniSubMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWxMiniSubMessageReq) ProtoMessage() {}

func (x *SendWxMiniSubMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_mqueue_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWxMiniSubMessageReq.ProtoReflect.Descriptor instead.
func (*SendWxMiniSubMessageReq) Descriptor() ([]byte, []int) {
	return file_mqueue_proto_rawDescGZIP(), []int{4}
}

func (x *SendWxMiniSubMessageReq) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *SendWxMiniSubMessageReq) GetTemplateID() string {
	if x != nil {
		return x.TemplateID
	}
	return ""
}

func (x *SendWxMiniSubMessageReq) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *SendWxMiniSubMessageReq) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendWxMiniSubMessageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendWxMiniSubMessageResp) Reset() {
	*x = SendWxMiniSubMessageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqueue_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendWxMiniSubMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWxMiniSubMessageResp) ProtoMessage() {}

func (x *SendWxMiniSubMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_mqueue_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWxMiniSubMessageResp.ProtoReflect.Descriptor instead.
func (*SendWxMiniSubMessageResp) Descriptor() ([]byte, []int) {
	return file_mqueue_proto_rawDescGZIP(), []int{5}
}

var File_mqueue_proto protoreflect.FileDescriptor

var file_mqueue_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x2e, 0x0a, 0x1c, 0x41, 0x71, 0x44, 0x65, 0x66, 0x65, 0x72, 0x48, 0x6f, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x73, 0x6e, 0x22, 0x1f, 0x0a, 0x1d, 0x41, 0x71, 0x44, 0x65, 0x66, 0x65, 0x72, 0x48, 0x6f, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x51, 0x0a, 0x17, 0x4b, 0x71, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x79, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x61, 0x79,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1a, 0x0a, 0x18, 0x4b, 0x71, 0x50, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x22, 0xd9, 0x01, 0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x78, 0x4d, 0x69, 0x6e,
	0x69, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x4f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x39, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x57, 0x78, 0x4d, 0x69, 0x6e, 0x69, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x37, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x1a,
	0x0a, 0x18, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x78, 0x4d, 0x69, 0x6e, 0x69, 0x53, 0x75, 0x62, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x32, 0x90, 0x02, 0x0a, 0x06, 0x6d,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x12, 0x60, 0x0a, 0x19, 0x61, 0x71, 0x44, 0x65, 0x66, 0x65, 0x72,
	0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x12, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x71, 0x44, 0x65, 0x66, 0x65, 0x72, 0x48,
	0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x71, 0x44, 0x65, 0x66, 0x65,
	0x72, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x51, 0x0a, 0x14, 0x6b, 0x71, 0x50, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x71, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x70,
	0x62, 0x2e, 0x4b, 0x71, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x51, 0x0a, 0x14, 0x73, 0x65,
	0x6e, 0x64, 0x57, 0x78, 0x4d, 0x69, 0x6e, 0x69, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x78, 0x4d, 0x69,
	0x6e, 0x69, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x78, 0x4d, 0x69, 0x6e, 0x69, 0x53,
	0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mqueue_proto_rawDescOnce sync.Once
	file_mqueue_proto_rawDescData = file_mqueue_proto_rawDesc
)

func file_mqueue_proto_rawDescGZIP() []byte {
	file_mqueue_proto_rawDescOnce.Do(func() {
		file_mqueue_proto_rawDescData = protoimpl.X.CompressGZIP(file_mqueue_proto_rawDescData)
	})
	return file_mqueue_proto_rawDescData
}

var file_mqueue_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_mqueue_proto_goTypes = []interface{}{
	(*AqDeferHomestayOrderCloseReq)(nil),  // 0: pb.AqDeferHomestayOrderCloseReq
	(*AqDeferHomestayOrderCloseResp)(nil), // 1: pb.AqDeferHomestayOrderCloseResp
	(*KqPaymenStatusUpdateReq)(nil),       // 2: pb.KqPaymenStatusUpdateReq
	(*KqPaymenStatusUpdateResp)(nil),      // 3: pb.KqPaymenStatusUpdateResp
	(*SendWxMiniSubMessageReq)(nil),       // 4: pb.SendWxMiniSubMessageReq
	(*SendWxMiniSubMessageResp)(nil),      // 5: pb.SendWxMiniSubMessageResp
	nil,                                   // 6: pb.SendWxMiniSubMessageReq.DataEntry
}
var file_mqueue_proto_depIdxs = []int32{
	6, // 0: pb.SendWxMiniSubMessageReq.Data:type_name -> pb.SendWxMiniSubMessageReq.DataEntry
	0, // 1: pb.mqueue.aqDeferHomestayOrderClose:input_type -> pb.AqDeferHomestayOrderCloseReq
	2, // 2: pb.mqueue.kqPaymenStatusUpdate:input_type -> pb.KqPaymenStatusUpdateReq
	4, // 3: pb.mqueue.sendWxMiniSubMessage:input_type -> pb.SendWxMiniSubMessageReq
	1, // 4: pb.mqueue.aqDeferHomestayOrderClose:output_type -> pb.AqDeferHomestayOrderCloseResp
	3, // 5: pb.mqueue.kqPaymenStatusUpdate:output_type -> pb.KqPaymenStatusUpdateResp
	5, // 6: pb.mqueue.sendWxMiniSubMessage:output_type -> pb.SendWxMiniSubMessageResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mqueue_proto_init() }
func file_mqueue_proto_init() {
	if File_mqueue_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mqueue_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AqDeferHomestayOrderCloseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mqueue_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AqDeferHomestayOrderCloseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mqueue_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KqPaymenStatusUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mqueue_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KqPaymenStatusUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mqueue_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendWxMiniSubMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mqueue_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendWxMiniSubMessageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mqueue_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mqueue_proto_goTypes,
		DependencyIndexes: file_mqueue_proto_depIdxs,
		MessageInfos:      file_mqueue_proto_msgTypes,
	}.Build()
	File_mqueue_proto = out.File
	file_mqueue_proto_rawDesc = nil
	file_mqueue_proto_goTypes = nil
	file_mqueue_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MqueueClient is the client API for Mqueue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MqueueClient interface {
	//添加民宿订单延迟关闭到asynq队列
	AqDeferHomestayOrderClose(ctx context.Context, in *AqDeferHomestayOrderCloseReq, opts ...grpc.CallOption) (*AqDeferHomestayOrderCloseResp, error)
	//支付流水状态变更发送到kq
	KqPaymenStatusUpdate(ctx context.Context, in *KqPaymenStatusUpdateReq, opts ...grpc.CallOption) (*KqPaymenStatusUpdateResp, error)
	//发送微信小程序订阅消息
	SendWxMiniSubMessage(ctx context.Context, in *SendWxMiniSubMessageReq, opts ...grpc.CallOption) (*SendWxMiniSubMessageResp, error)
}

type mqueueClient struct {
	cc grpc.ClientConnInterface
}

func NewMqueueClient(cc grpc.ClientConnInterface) MqueueClient {
	return &mqueueClient{cc}
}

func (c *mqueueClient) AqDeferHomestayOrderClose(ctx context.Context, in *AqDeferHomestayOrderCloseReq, opts ...grpc.CallOption) (*AqDeferHomestayOrderCloseResp, error) {
	out := new(AqDeferHomestayOrderCloseResp)
	err := c.cc.Invoke(ctx, "/pb.mqueue/aqDeferHomestayOrderClose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mqueueClient) KqPaymenStatusUpdate(ctx context.Context, in *KqPaymenStatusUpdateReq, opts ...grpc.CallOption) (*KqPaymenStatusUpdateResp, error) {
	out := new(KqPaymenStatusUpdateResp)
	err := c.cc.Invoke(ctx, "/pb.mqueue/kqPaymenStatusUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mqueueClient) SendWxMiniSubMessage(ctx context.Context, in *SendWxMiniSubMessageReq, opts ...grpc.CallOption) (*SendWxMiniSubMessageResp, error) {
	out := new(SendWxMiniSubMessageResp)
	err := c.cc.Invoke(ctx, "/pb.mqueue/sendWxMiniSubMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MqueueServer is the server API for Mqueue service.
type MqueueServer interface {
	//添加民宿订单延迟关闭到asynq队列
	AqDeferHomestayOrderClose(context.Context, *AqDeferHomestayOrderCloseReq) (*AqDeferHomestayOrderCloseResp, error)
	//支付流水状态变更发送到kq
	KqPaymenStatusUpdate(context.Context, *KqPaymenStatusUpdateReq) (*KqPaymenStatusUpdateResp, error)
	//发送微信小程序订阅消息
	SendWxMiniSubMessage(context.Context, *SendWxMiniSubMessageReq) (*SendWxMiniSubMessageResp, error)
}

// UnimplementedMqueueServer can be embedded to have forward compatible implementations.
type UnimplementedMqueueServer struct {
}

func (*UnimplementedMqueueServer) AqDeferHomestayOrderClose(context.Context, *AqDeferHomestayOrderCloseReq) (*AqDeferHomestayOrderCloseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AqDeferHomestayOrderClose not implemented")
}
func (*UnimplementedMqueueServer) KqPaymenStatusUpdate(context.Context, *KqPaymenStatusUpdateReq) (*KqPaymenStatusUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KqPaymenStatusUpdate not implemented")
}
func (*UnimplementedMqueueServer) SendWxMiniSubMessage(context.Context, *SendWxMiniSubMessageReq) (*SendWxMiniSubMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendWxMiniSubMessage not implemented")
}

func RegisterMqueueServer(s *grpc.Server, srv MqueueServer) {
	s.RegisterService(&_Mqueue_serviceDesc, srv)
}

func _Mqueue_AqDeferHomestayOrderClose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AqDeferHomestayOrderCloseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqueueServer).AqDeferHomestayOrderClose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.mqueue/AqDeferHomestayOrderClose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqueueServer).AqDeferHomestayOrderClose(ctx, req.(*AqDeferHomestayOrderCloseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mqueue_KqPaymenStatusUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KqPaymenStatusUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqueueServer).KqPaymenStatusUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.mqueue/KqPaymenStatusUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqueueServer).KqPaymenStatusUpdate(ctx, req.(*KqPaymenStatusUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mqueue_SendWxMiniSubMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendWxMiniSubMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqueueServer).SendWxMiniSubMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.mqueue/SendWxMiniSubMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqueueServer).SendWxMiniSubMessage(ctx, req.(*SendWxMiniSubMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mqueue_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.mqueue",
	HandlerType: (*MqueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "aqDeferHomestayOrderClose",
			Handler:    _Mqueue_AqDeferHomestayOrderClose_Handler,
		},
		{
			MethodName: "kqPaymenStatusUpdate",
			Handler:    _Mqueue_KqPaymenStatusUpdate_Handler,
		},
		{
			MethodName: "sendWxMiniSubMessage",
			Handler:    _Mqueue_SendWxMiniSubMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mqueue.proto",
}
