// Code generated by protoc-gen-go. DO NOT EDIT.
// source: identity.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenerateTokenReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateTokenReq) Reset()         { *m = GenerateTokenReq{} }
func (m *GenerateTokenReq) String() string { return proto.CompactTextString(m) }
func (*GenerateTokenReq) ProtoMessage()    {}
func (*GenerateTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{0}
}

func (m *GenerateTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateTokenReq.Unmarshal(m, b)
}
func (m *GenerateTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateTokenReq.Marshal(b, m, deterministic)
}
func (m *GenerateTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateTokenReq.Merge(m, src)
}
func (m *GenerateTokenReq) XXX_Size() int {
	return xxx_messageInfo_GenerateTokenReq.Size(m)
}
func (m *GenerateTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateTokenReq proto.InternalMessageInfo

func (m *GenerateTokenReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GenerateTokenResp struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	AccessExpire         int64    `protobuf:"varint,2,opt,name=accessExpire,proto3" json:"accessExpire,omitempty"`
	RefreshAfter         int64    `protobuf:"varint,3,opt,name=refreshAfter,proto3" json:"refreshAfter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateTokenResp) Reset()         { *m = GenerateTokenResp{} }
func (m *GenerateTokenResp) String() string { return proto.CompactTextString(m) }
func (*GenerateTokenResp) ProtoMessage()    {}
func (*GenerateTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{1}
}

func (m *GenerateTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateTokenResp.Unmarshal(m, b)
}
func (m *GenerateTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateTokenResp.Marshal(b, m, deterministic)
}
func (m *GenerateTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateTokenResp.Merge(m, src)
}
func (m *GenerateTokenResp) XXX_Size() int {
	return xxx_messageInfo_GenerateTokenResp.Size(m)
}
func (m *GenerateTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateTokenResp proto.InternalMessageInfo

func (m *GenerateTokenResp) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GenerateTokenResp) GetAccessExpire() int64 {
	if m != nil {
		return m.AccessExpire
	}
	return 0
}

func (m *GenerateTokenResp) GetRefreshAfter() int64 {
	if m != nil {
		return m.RefreshAfter
	}
	return 0
}

type ClearTokenReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearTokenReq) Reset()         { *m = ClearTokenReq{} }
func (m *ClearTokenReq) String() string { return proto.CompactTextString(m) }
func (*ClearTokenReq) ProtoMessage()    {}
func (*ClearTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{2}
}

func (m *ClearTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearTokenReq.Unmarshal(m, b)
}
func (m *ClearTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearTokenReq.Marshal(b, m, deterministic)
}
func (m *ClearTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearTokenReq.Merge(m, src)
}
func (m *ClearTokenReq) XXX_Size() int {
	return xxx_messageInfo_ClearTokenReq.Size(m)
}
func (m *ClearTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_ClearTokenReq proto.InternalMessageInfo

func (m *ClearTokenReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ClearTokenResp struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearTokenResp) Reset()         { *m = ClearTokenResp{} }
func (m *ClearTokenResp) String() string { return proto.CompactTextString(m) }
func (*ClearTokenResp) ProtoMessage()    {}
func (*ClearTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{3}
}

func (m *ClearTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearTokenResp.Unmarshal(m, b)
}
func (m *ClearTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearTokenResp.Marshal(b, m, deterministic)
}
func (m *ClearTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearTokenResp.Merge(m, src)
}
func (m *ClearTokenResp) XXX_Size() int {
	return xxx_messageInfo_ClearTokenResp.Size(m)
}
func (m *ClearTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_ClearTokenResp proto.InternalMessageInfo

func (m *ClearTokenResp) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type ValidateTokenReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateTokenReq) Reset()         { *m = ValidateTokenReq{} }
func (m *ValidateTokenReq) String() string { return proto.CompactTextString(m) }
func (*ValidateTokenReq) ProtoMessage()    {}
func (*ValidateTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{4}
}

func (m *ValidateTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateTokenReq.Unmarshal(m, b)
}
func (m *ValidateTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateTokenReq.Marshal(b, m, deterministic)
}
func (m *ValidateTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateTokenReq.Merge(m, src)
}
func (m *ValidateTokenReq) XXX_Size() int {
	return xxx_messageInfo_ValidateTokenReq.Size(m)
}
func (m *ValidateTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateTokenReq proto.InternalMessageInfo

func (m *ValidateTokenReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ValidateTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidateTokenResp struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateTokenResp) Reset()         { *m = ValidateTokenResp{} }
func (m *ValidateTokenResp) String() string { return proto.CompactTextString(m) }
func (*ValidateTokenResp) ProtoMessage()    {}
func (*ValidateTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{5}
}

func (m *ValidateTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateTokenResp.Unmarshal(m, b)
}
func (m *ValidateTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateTokenResp.Marshal(b, m, deterministic)
}
func (m *ValidateTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateTokenResp.Merge(m, src)
}
func (m *ValidateTokenResp) XXX_Size() int {
	return xxx_messageInfo_ValidateTokenResp.Size(m)
}
func (m *ValidateTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateTokenResp proto.InternalMessageInfo

func (m *ValidateTokenResp) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*GenerateTokenReq)(nil), "pb.GenerateTokenReq")
	proto.RegisterType((*GenerateTokenResp)(nil), "pb.GenerateTokenResp")
	proto.RegisterType((*ClearTokenReq)(nil), "pb.ClearTokenReq")
	proto.RegisterType((*ClearTokenResp)(nil), "pb.ClearTokenResp")
	proto.RegisterType((*ValidateTokenReq)(nil), "pb.ValidateTokenReq")
	proto.RegisterType((*ValidateTokenResp)(nil), "pb.ValidateTokenResp")
}

func init() { proto.RegisterFile("identity.proto", fileDescriptor_61c7956abb761639) }

var fileDescriptor_61c7956abb761639 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xd9, 0x14, 0x4b, 0x1d, 0xed, 0xd2, 0x1d, 0xaa, 0x2c, 0x3d, 0x2d, 0xf1, 0xa0, 0x78,
	0xd8, 0x83, 0xbd, 0x7a, 0x50, 0x44, 0xc4, 0xeb, 0x22, 0xde, 0xf7, 0xcf, 0x54, 0x97, 0x2d, 0x9b,
	0x98, 0x44, 0xd1, 0x83, 0x9f, 0xcc, 0x2f, 0x27, 0x9b, 0xa8, 0xa4, 0xa9, 0xa0, 0xc7, 0x79, 0xbc,
	0xcc, 0x9b, 0xdf, 0x23, 0x10, 0xb7, 0x0d, 0xf5, 0xa6, 0x35, 0x6f, 0xb9, 0x54, 0xc2, 0x08, 0x64,
	0xb2, 0xe2, 0xa7, 0x30, 0xbb, 0xa1, 0x9e, 0x54, 0x69, 0xe8, 0x4e, 0x74, 0xd4, 0x17, 0xf4, 0x84,
	0x87, 0x30, 0x7e, 0xd6, 0xa4, 0x6e, 0x9b, 0x34, 0xca, 0xa2, 0x93, 0x51, 0xf1, 0x35, 0xf1, 0x77,
	0x48, 0x02, 0xaf, 0x96, 0x98, 0xc1, 0x5e, 0x59, 0xd7, 0xa4, 0xb5, 0x95, 0xec, 0x8b, 0xdd, 0xc2,
	0x97, 0x90, 0xc3, 0xbe, 0x1b, 0xaf, 0x5f, 0x65, 0xab, 0x28, 0x65, 0x76, 0xe9, 0x86, 0x36, 0x78,
	0x14, 0xad, 0x14, 0xe9, 0xc7, 0xcb, 0x95, 0x21, 0x95, 0x8e, 0x9c, 0xc7, 0xd7, 0xf8, 0x31, 0x4c,
	0xaf, 0xd6, 0x54, 0xaa, 0x3f, 0xef, 0xcc, 0x20, 0xf6, 0x8d, 0x5a, 0x62, 0x0c, 0x4c, 0x74, 0xd6,
	0x35, 0x29, 0x98, 0xe8, 0xf8, 0x05, 0xcc, 0xee, 0xcb, 0x75, 0xdb, 0xfc, 0x83, 0x1a, 0xe7, 0xb0,
	0x63, 0x2c, 0x1a, 0xb3, 0x68, 0x6e, 0xe0, 0x47, 0x90, 0x04, 0x1b, 0xb6, 0x63, 0xce, 0x3e, 0x22,
	0x98, 0x7c, 0x77, 0x8e, 0xe7, 0x30, 0x7d, 0xf0, 0xdb, 0xc3, 0x79, 0x2e, 0xab, 0x3c, 0x2c, 0x7f,
	0x71, 0xf0, 0x8b, 0xaa, 0x25, 0x2e, 0x01, 0xea, 0x1f, 0x26, 0x4c, 0x06, 0xd3, 0x46, 0x19, 0x0b,
	0x0c, 0x25, 0x2d, 0x87, 0xc8, 0x17, 0xff, 0x48, 0x17, 0x19, 0x92, 0xbb, 0xc8, 0x2d, 0x9a, 0x6a,
	0x6c, 0x7f, 0xc9, 0xf2, 0x33, 0x00, 0x00, 0xff, 0xff, 0x71, 0x64, 0x28, 0x9c, 0x37, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IdentityClient is the client API for Identity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentityClient interface {
	//生成token，只针对用户服务开放访问
	GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenResp, error)
	//清除token，只针对用户服务开放访问
	ClearToken(ctx context.Context, in *ClearTokenReq, opts ...grpc.CallOption) (*ClearTokenResp, error)
	//validateToken ，只很对用户服务、授权服务api开放
	ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error)
}

type identityClient struct {
	cc *grpc.ClientConn
}

func NewIdentityClient(cc *grpc.ClientConn) IdentityClient {
	return &identityClient{cc}
}

func (c *identityClient) GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenResp, error) {
	out := new(GenerateTokenResp)
	err := c.cc.Invoke(ctx, "/pb.identity/generateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) ClearToken(ctx context.Context, in *ClearTokenReq, opts ...grpc.CallOption) (*ClearTokenResp, error) {
	out := new(ClearTokenResp)
	err := c.cc.Invoke(ctx, "/pb.identity/clearToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error) {
	out := new(ValidateTokenResp)
	err := c.cc.Invoke(ctx, "/pb.identity/validateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServer is the server API for Identity service.
type IdentityServer interface {
	//生成token，只针对用户服务开放访问
	GenerateToken(context.Context, *GenerateTokenReq) (*GenerateTokenResp, error)
	//清除token，只针对用户服务开放访问
	ClearToken(context.Context, *ClearTokenReq) (*ClearTokenResp, error)
	//validateToken ，只很对用户服务、授权服务api开放
	ValidateToken(context.Context, *ValidateTokenReq) (*ValidateTokenResp, error)
}

// UnimplementedIdentityServer can be embedded to have forward compatible implementations.
type UnimplementedIdentityServer struct {
}

func (*UnimplementedIdentityServer) GenerateToken(ctx context.Context, req *GenerateTokenReq) (*GenerateTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateToken not implemented")
}
func (*UnimplementedIdentityServer) ClearToken(ctx context.Context, req *ClearTokenReq) (*ClearTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearToken not implemented")
}
func (*UnimplementedIdentityServer) ValidateToken(ctx context.Context, req *ValidateTokenReq) (*ValidateTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}

func RegisterIdentityServer(s *grpc.Server, srv IdentityServer) {
	s.RegisterService(&_Identity_serviceDesc, srv)
}

func _Identity_GenerateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).GenerateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.identity/GenerateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).GenerateToken(ctx, req.(*GenerateTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_ClearToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).ClearToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.identity/ClearToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).ClearToken(ctx, req.(*ClearTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.identity/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).ValidateToken(ctx, req.(*ValidateTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Identity_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.identity",
	HandlerType: (*IdentityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "generateToken",
			Handler:    _Identity_GenerateToken_Handler,
		},
		{
			MethodName: "clearToken",
			Handler:    _Identity_ClearToken_Handler,
		},
		{
			MethodName: "validateToken",
			Handler:    _Identity_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity.proto",
}
